{
 "title": "NGINX ModSecurity OWASP CRS for JSON formatted logs",
 "description": "Dashboard to work with ModSecurity and the OWASP Coreruleset.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": "cloud,wiki,grafana,shop,mineos,sonarr,radarr,gitea,mountaineering,heimdall,yurt"
   }
  ]
 },
 "panels": [
  {
   "title": "Top Attackers",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (client_ip) (count_over_time({job=\"network/ingress-nginx\"} \n|~ `ModSecurity` != `http_referrer` \n| json messages_details_match=\"transaction.messages[0].details.match\", \nmessages_details_reference=\"transaction.messages[0].details.reference\", \nmessages_details_ruleId=\"transaction.messages[0].details.ruleId\", \nmessages_details_file=\"transaction.messages[0].details.file\", \nmessages_details_lineNumber=\"transaction.messages[0].details.lineNumber\", \nmessages_details_data=\"transaction.messages[0].details.data\", \nmessages_details_severity=\"transaction.messages[0].details.severity\", \nmessages_details_ver=\"transaction.messages[0].details.ver\", \nmessages_details_rev=\"transaction.messages[0].details.rev\", \nmessages_details_tags=\"transaction.messages[0].details.tags\", \nmessages_details_maturity=\"transaction.messages[0].details.maturity\",\nmessages_details_accuracy=\"transaction.messages[0].details.accuracy\", \ntransaction_date=\"transaction.time_stamp\", \nclient_ip=\"transaction.client_ip\", \ntransaction_host_ip=\"transaction.host_ip\", \ntransaction_host_port=\"transaction.host_port\", \ntranaction_request_uri=\"transaction.request.uri\" | __error__=\"\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Detection Activity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum by (severity) (count_over_time({job=\"network/ingress-nginx\"} \n|~ `ModSecurity` != `http_referrer` \n| json messages_details_match=\"transaction.messages[0].details.match\", \nmessages_details_reference=\"transaction.messages[0].details.reference\", \nmessages_details_ruleId=\"transaction.messages[0].details.ruleId\", \nmessages_details_file=\"transaction.messages[0].details.file\", \nmessages_details_lineNumber=\"transaction.messages[0].details.lineNumber\", \nmessages_details_data=\"transaction.messages[0].details.data\", \nseverity=\"transaction.messages[0].details.severity\", \nmessages_details_ver=\"transaction.messages[0].details.ver\", \nmessages_details_rev=\"transaction.messages[0].details.rev\", \nmessages_details_tags=\"transaction.messages[0].details.tags\", \nmessages_details_maturity=\"transaction.messages[0].details.maturity\", \nmessages_details_accuracy=\"transaction.messages[0].details.accuracy\", \ntransaction_date=\"transaction.time_stamp\", \ntransaction_client_ip=\"transaction.client_ip\", \ntransaction_host_ip=\"transaction.host_ip\", \ntransaction_host_port=\"transaction.host_port\", \ntranaction_request_uri=\"transaction.request.uri\" | __error__=\"\" [$__interval]))"
    },
    {
     "expr": "{job=\"nginx_error\"}"
    }
   ]
  },
  {
   "title": "Rules by Host",
   "type": "stat",
   "gridPos": { "h": 22, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (host_ip,message,ruleId) (count_over_time({job=\"network/ingress-nginx\"} \n|~ `ModSecurity` != `http_referrer` \n| json messages_details_match=\"transaction.messages[0].details.match\", \nmessages_details_reference=\"transaction.messages[0].details.reference\", \nruleId=\"transaction.messages[0].details.ruleId\", \nmessages_details_file=\"transaction.messages[0].details.file\", \nmessages_details_lineNumber=\"transaction.messages[0].details.lineNumber\", \nmessages_details_data=\"transaction.messages[0].details.data\", \nmessages_details_severity=\"transaction.messages[0].details.severity\", \nmessages_details_ver=\"transaction.messages[0].details.ver\", \nmessages_details_rev=\"transaction.messages[0].details.rev\", \nmessages_details_tags=\"transaction.messages[0].details.tags\", \nmessages_details_maturity=\"transaction.messages[0].details.maturity\", \nmessages_details_accuracy=\"transaction.messages[0].details.accuracy\", \ntransaction_date=\"transaction.time_stamp\", \ntransaction_client_ip=\"transaction.client_ip\", \nhost_ip=\"transaction.host_ip\", \ntransaction_host_port=\"transaction.host_port\", \ntranaction_request_uri=\"transaction.request.uri\", \nmessage=\"transaction.messages[0].message\" |  __error__=\"\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Anomaly Detection Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 15, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{job=\"network/ingress-nginx\"} |~ `ModSecurity` != `http_referrer` | json messages_details_match=\"transaction.messages[0].details.match\", messages_details_reference=\"transaction.messages[0].details.reference\", messages_details_ruleId=\"transaction.messages[0].details.ruleId\", messages_details_file=\"transaction.messages[0].details.file\", messages_details_lineNumber=\"transaction.messages[0].details.lineNumber\", messages_details_data=\"transaction.messages[0].details.data\", messages_details_severity=\"transaction.messages[0].details.severity\", messages_details_ver=\"transaction.messages[0].details.ver\", messages_details_rev=\"transaction.messages[0].details.rev\", messages_details_tags=\"transaction.messages[0].details.tags\", messages_details_maturity=\"transaction.messages[0].details.maturity\", messages_details_accuracy=\"transaction.messages[0].details.accuracy\", transaction_date=\"transaction.time_stamp\", transaction_client_ip=\"transaction.client_ip\", transaction_host_ip=\"transaction.host_ip\", transaction_host_port=\"transaction.host_port\", tranaction_request_uri=\"transaction.request.uri\", messages_message=\"transaction.messages[0].message\"\n\n| line_format \"⚠️ Anomaly Detected: \\nDate: {{.transaction_date}} \\nSeverity {{.messages_details_severity}} \\nRule: {{.messages_details_ruleId}} \\nReason: {{.messages_message}} \\nEvent: request for {{.transaction_host_ip}}:{{.transaction_host_port}}{{.tranaction_request_uri}} from {{.transaction_client_ip}}\\n\""
    }
   ]
  }
 ]
}